services:
  # Main Backend Service
  - type: web
    name: trading-journal-backend
    env: python
    plan: starter
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y --no-install-recommends \
          gcc \
          python3.11-dev \
          libpq-dev \
          libffi-dev \
          libssl-dev \
          && rm -rf /var/lib/apt/lists/*
      
      # Install Python dependencies with proper version handling
      export PYTHONPATH=/opt/render/project/src
      python3.11 -m pip install --upgrade pip setuptools wheel
      python3.11 -m pip install --no-cache-dir -r requirements.txt
      
      # Create necessary directories
      mkdir -p instance
      
    startCommand: >
      gunicorn --worker-class gthread 
      --workers 4 
      --threads 2 
      --timeout 120 
      --keep-alive 5 
      --bind 0.0.0.0:$PORT 
      --log-level=info 
      --access-logfile - 
      --error-logfile - 
      app:app
      
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."
      - key: PYTHON_FULL_VERSION
        value: "3.11.0"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_DEBUG
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: trading-journal-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: GUNICORN_CMD_ARGS
        value: "--worker-class=gthread --workers=4 --threads=2 --timeout=120 --keep-alive=5"
    healthCheckPath: /api/auth/test

  # Frontend Service
  - type: web
    name: trading-bot-frontend
    env: node
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: /api

  # Binance API Service
  - type: web
    name: binance-service
    env: node
    buildCommand: cd binance_service && npm install
    startCommand: cd binance_service && node server.js
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: "18.17.0"
      - key: PORT
        value: 5010
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_SECRET_KEY
        sync: false
    healthCheckPath: /health

  # Forex Data Service
  - type: web
    name: forex-data-service
    env: python
    buildCommand: |
      cd forex_data_service
      python3.11 -m pip install --upgrade pip setuptools wheel
      python3.11 -m pip install -r requirements.txt
    startCommand: cd forex_data_service && python3.11 server.py
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: 3004
    healthCheckPath: /health

  # Customer Service
  - type: web
    name: customer-service
    env: node
    buildCommand: cd customer-service && npm install
    startCommand: cd customer-service && node server.js
    plan: starter
    envVars:
      - key: PORT
        value: 3005
    healthCheckPath: /health

  # Lot Size Calculator Service
  - type: web
    name: lot-size-calculator
    env: node
    buildCommand: cd lot_size_calculator && npm install
    startCommand: cd lot_size_calculator && node server.js
    plan: starter
    envVars:
      - key: PORT
        value: 3006
    healthCheckPath: /health

databases:
  - name: trading-journal-db
    plan: free
    databaseName: trading_journal
    user: trading_journal_user
