services:
  # Main Trading Journal Frontend
  - type: web
    name: trading-journal-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: trading-journal-db
    plan: free
    databaseName: trading_journal
    user: trading_journal_user
